laraveldarbs/routes/web.php
<?php

use App\Http\Controllers\Auth\ImageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TournamentController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('/team', TeamController::class);
Route::resource('/tournament', TournamentController::class);
Route::post('/tournament/{tournament}/addStats', [TournamentController::class, 'addStats'])->name('tournament.addStats');
Route::get('/tournament/{tournament}/getChangeStatsView', [TournamentController::class, 'getChangeStatsView'])->name('tournament.getChangeStatsView');
Route::get('/tournament/{tournament}/changeScore', [TournamentController::class, 'changeScore'])->name('tournament.changeScore');
Route::put('/tournament/{tournament}/updateScore', [TournamentController::class, 'updateScore'])->name('tournament.updateScore');
Route::get('/image', [ImageController::class, 'index'])->name('image.index');
Route::get('/changeImage', [ImageController::class, 'changeImage'])->name('image.changeImage');
Route::post('/uploadImage', [ImageController::class, 'uploadImage'])->name('image.uploadImage');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

laraveldarbs/app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    protected $primaryKey = 'id';

    public function attachUser() //function that adds users to model
    {
        return $this->belongsToMany(User::class);
    }
}

laraveldarbs/app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Team;
use App\Models\Tournament;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $teams = Team::all();
        return view('team.index', compact('teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == 'admin') {
                $allUsers = User::all();
                $users = $this->getTeamless($allUsers->all());

                return view('team.create', compact('users'));
            }
        }

        return redirect()->route('team.index')->with('error', 'Only admin can access create.');
    }

    public function getTeamless($users)
    {
        $teamless = [];
        foreach ($users as $user) {
            $count = DB::table('team_user')->get()->where('user_id', $user->id)->count();
            if ($count == 0) {
                array_push($teamless, $user);
            }
        }

        return $teamless;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        if ($request->users == null || sizeof($request->users) != 6) {
            return redirect()->route('team.create')->with('error', 'Team must consist of six players!');
        }

        $teamName = [
            'name' => $request->name
        ];

        $team = Team::create($teamName);

        $users = $request->users;

        foreach ($users as $user) {
            $team->attachUser()->attach($user);//tiek saglabāts team user starptabulā
        }

        return redirect()->route('team.index')->with('success', 'Team was added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Team  $team
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(Team $team)//parāda komandu ar useriem
    {
        $playerIds = DB::table('team_user')->where('team_id', $team->id)->get('user_id');
        $players = [];

        foreach ($playerIds as $id) {
            array_push($players, User::find($id->user_id));
        }

        return view('team.show', compact('team', 'players'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Team  $team
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Team $team)//rediģēt komandu
    {
        $allUsers = User::all();
        $users = $this->getTeamless($allUsers->all());//nav komandā
        $teamPlayers = $this->getTeamMembers($team);//ir komandā

        foreach ($teamPlayers as $teamPlayer) {
            array_push($users, $teamPlayer);//apvieno vienā sarakstā
        }

        return view('team.edit', compact('users', 'teamPlayers', 'team'));
    }

    public function getTeamMembers($team)
    {
        $teamPlayers = [];

        $teamPlayerIds =  DB::table('team_user')->where('team_id', $team->id)->get('user_id');

        foreach ($teamPlayerIds as $teamPlayerId) {
            array_push($teamPlayers, User::find($teamPlayerId->user_id));
        }

        return $teamPlayers;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Team  $team
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Team $team)
    {
        if ($request->users == null || sizeof($request->users) != 6) {
            return redirect()->route('team.edit', $team)->with('error', 'Team must consist of six players!');
        }

        $teamName = [
            'name' => $request->name
        ];

        $team->update($teamName);
        $this->removeDataBeforeUpdate($team);
        $users = $request->users;

        foreach ($users as $user) {
            $team->attachUser()->attach($user);
        }

        return redirect()->route('team.index')->with('success', 'Team was edited.');
    }

    public function removeDataBeforeUpdate($team)
    {
        DB::table('team_user')->where('team_id', $team->id)->delete();
    }

    public function deleteTournament($team) {
        $tournamentId = DB::table('team_tournament')->where('team_id', $team->id)->get('tournament_id')->first();
        app(TournamentController::class)->destroy(Tournament::find($tournamentId->tournament_id));
        DB::table('team_tournament')->where('tournament_id', $tournamentId->tournament_id)->delete();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Team  $team
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Team $team)
    {
        $this->deleteTournament($team);
        $this->removeDataBeforeUpdate($team);
        $team->delete();

        return redirect()->route('team.index')->with('success', 'Team was successfully deleted.');
    }
}

laraveldarbs/resources/views/team/create.blade.php
@extends('layouts.app')
@section('content')

<div class="form-container">
        <form class="new-challenge-form" method="post" enctype="multipart/form-data" action="{{ route('team.store') }}">
    @csrf
            <h3>New Team</h3>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" name="name" required minlength="4">
            </div>
            <div class="form-group">
                <label>Users</label>
                @if(json_encode($users) != '[]')
                <select id="user-select" name="users[]" multiple="multiple" class="form-control" >
                    @foreach($users as $user)
                        <option value="{{ $user->id }}">
                            {{ $user->name }}
                        </option>
                    @endforeach
                    @else
                        <div class="form-control">{{ __('There are no users') }}</div>
                @endif
                </select>
            </div>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Submit</button>
        </form>
    </div>

@endsection

laraveldarbs/resources/views/team/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="form-container">
        <form class="new-challenge-form" method="POST" enctype="multipart/form-data" action="{{ route('team.update', $team) }}">
            @method('PUT')
            @csrf
            <h3>New Team</h3>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" name="name" required minlength="4" value="{{ $team->name }}">
            </div>
            <div class="form-group">
                <label>Users</label>
                @if(json_encode($users) != '[]')
                    <select id="user-select" name="users[]" multiple="multiple" class="form-control" >
                        @foreach($users as $user)
                            <option value="{{ $user->id }}" {{ isInList($teamPlayers, $user->id) ? 'selected' : ''  }}>
                                {{ $user->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no users') }}</div>
                        @endif
                    </select>
            </div>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Submit</button>
        </form>
    </div>

@endsection

laraveldarbs/resources/views/team/index.blade.php
@extends('layouts.app')
@section('content')
    <a class="btn btn-success" href="{{ route('team.create')  }}">Create team</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Team</th>
            <th scope="col">Created at</th>
            <th scope="col">Updated at</th>
            <th scope="col">Options</th>
        </tr>
        </thead>
        <tbody>
        @foreach($teams as $team)
            <tr>
                <td>{{ $team->name }}</td>
                <td>{{ $team->created_at }}</td>
                <td>{{ $team->updated_at }}</td>
                <td>
                    <form action="{{ route('team.destroy',$team) }}" method="POST">
                        <a href="{{ route('team.show', $team ) }}" class="btn btn-success">Look</a>
                        @auth()
                            @if(Auth::user()->role == 'admin')
                                <a href="{{ route('team.edit', $team) }}" class="btn btn-info">Edit</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            @endif
                        @endauth
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

laraveldarbs/resources/views/team/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="form-container">
            <h1>{{ $team->name  }}</h1>
            <div class="form-group">
                <h3>Players</h3>
                @if(json_encode($players) != '[]')
                        @foreach($players as $player)
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ asset(sprintf('/images/%s', $player->image))  }}" alt="Card image cap">
                                <div class="card-body">
                                    <p class="card-text">{{ $player->name  }}.</p>
                                </div>
                            </div>
                        @endforeach
                   @else
                   <div class="form-control">{{ __('There are no players.') }}</div>
                @endif
            </div>
    </div>

@endsection