laraveldarbs/routes/web.php
<?php

use App\Http\Controllers\Auth\ImageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TournamentController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('/team', TeamController::class);
Route::resource('/tournament', TournamentController::class);
Route::post('/tournament/{tournament}/addStats', [TournamentController::class, 'addStats'])->name('tournament.addStats');
Route::get('/tournament/{tournament}/getChangeStatsView', [TournamentController::class, 'getChangeStatsView'])->name('tournament.getChangeStatsView');
Route::get('/tournament/{tournament}/changeScore', [TournamentController::class, 'changeScore'])->name('tournament.changeScore');
Route::put('/tournament/{tournament}/updateScore', [TournamentController::class, 'updateScore'])->name('tournament.updateScore');
Route::get('/image', [ImageController::class, 'index'])->name('image.index');
Route::get('/changeImage', [ImageController::class, 'changeImage'])->name('image.changeImage');
Route::post('/uploadImage', [ImageController::class, 'uploadImage'])->name('image.uploadImage');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

laraveldarbs/app/Models/Tournament.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tournament extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'map_id',
        'score'
    ];

    protected $primaryKey = 'id';

    public function attachTeam() //function that adds users to model
    {
        return $this->belongsToMany(Team::class);
    }
}

laraveldarbs/app/Http/Controllers/TournamentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Team;
use App\Models\Tournament;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class TournamentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()//parāda turnīru sarakstu
    {
        $tournaments = Tournament::all();
        $maps = DB::table('map')->get()->all();
        $teams = Team::all();
        $tournamentTeam = DB::table('team_tournament')->get()->all();

        return view('tournament.index', compact('tournaments', 'maps', 'teams', 'tournamentTeam'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()//atlasa komandas, karti
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == 'admin') {
                $teams = Team::all();
                $maps = DB::table('map')->get()->all();
                return view('tournament.create', compact('teams', 'maps'));
            }
        }
        return redirect()->route('tournament.index')->with('error', 'Only admin can access create.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)//saglabā turnīru
    {
        $team1 = $request->team1;
        $team2 = $request->team2;

        if($team1 != $team2) {
            $tournamentData = [
                'name' => $request->name,
                'map_id' => $request->map_id
            ];

            $tournament = Tournament::create($tournamentData);

            $tournament->attachTeam()->attach($team1);
            $tournament->attachTeam()->attach($team2);

            return redirect()->route('tournament.index')->with('success', 'Tournament was added.');
        }

        return redirect()->route('tournament.create')->with('error', 'Same teams cant play with each other');
    }

    /**
     * @param Tournament $tournament
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function getChangeStatsView(Tournament $tournament) {
        $players = User::all();
        $stats = DB::table('stats_user')->get()->all();
        $map = DB::table('map')->where('id', $tournament->map_id)->first();
        $teamIds = DB::table('team_tournament')->where('tournament_id', $tournament->id)->get('team_id')->all();
        $team1 = Team::find($teamIds[0]->team_id);
        $team2 = Team::find($teamIds[1]->team_id);
        $playersTeam1 = $this->getTeamsPlayers($team1, $players);
        $playersTeam2 = $this->getTeamsPlayers($team2, $players);

        return view('tournament.showPlayerStats', compact('tournament', 'playersTeam1', 'playersTeam2', 'stats', 'map', 'team1', 'team2'));
    }

    /**
     * @param Request $request
     * @param Tournament $tournament
     * @return \Illuminate\Http\RedirectResponse
     */
    public function addStats(Request $request, Tournament $tournament): \Illuminate\Http\RedirectResponse
    {
        $teamIds = DB::table('team_tournament')->where('tournament_id', $tournament->id)->get('team_id')->all();
        $players = User::all();
        $team1 = Team::find($teamIds[0]->team_id);
        $team2 = Team::find($teamIds[1]->team_id);
        $playersTeam1 = $this->getTeamsPlayers($team1, $players);
        $playersTeam2 = $this->getTeamsPlayers($team2, $players);
        $this->addStatsToDB($playersTeam1, $request);
        $this->addStatsToDB($playersTeam2, $request);

        return redirect()->route('tournament.show', $tournament)->with('success', 'Tournament stats where refreshed.');

    }

    public function addStatsToDB($players, $request) {
        foreach ($players as $player) {
            $stats = [
                'user_id' => $player->id,
                'kills' => $request[sprintf('%skills', $player->id)],
                'assists' => $request[sprintf('%sassists', $player->id)],
                'deaths' => $request[sprintf('%sdeaths', $player->id)]
            ];

            DB::table('stats_user')->where('user_id', $player->id)->delete();
            DB::table('stats_user')->insert($stats);
        }
    }

    /**
     * @param Tournament $tournament
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function changeScore(Tournament $tournament) {
        return view('tournament.changeScore', compact('tournament'));
    }

    public function updateScore(Tournament $tournament, Request $request) {
        if (preg_match('/^[0-9]?[0-9][:][0-9]?[0-9]$/', $request->score)) {
            $tournament->update($request->all());

            return redirect()->route('tournament.show', $tournament)->with('success', 'Tournament score was refreshed.');
        }
        return redirect()->route('tournament.changeScore', $tournament)->with('error', 'Score is invalid.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function show(Tournament $tournament)
    {
        $players = User::all();
        $stats = DB::table('stats_user')->get()->all();
        $map = DB::table('map')->where('id', $tournament->map_id)->first();
        $teamIds = DB::table('team_tournament')->where('tournament_id', $tournament->id)->get('team_id')->all();
        $team1 = Team::find($teamIds[0]->team_id);
        $team2 = Team::find($teamIds[1]->team_id);
        $playersTeam1 = $this->getTeamsPlayers($team1, $players);
        $playersTeam2 = $this->getTeamsPlayers($team2, $players);

        return view('tournament.show', compact('tournament', 'playersTeam1', 'playersTeam2', 'stats', 'map', 'team1', 'team2'));
    }

    /**
     * @param $team
     * @param $allPlayers
     * @return array
     */
    public function getTeamsPlayers($team, $allPlayers): array
    {
        $playerIds = DB::table('team_user')->where('team_id', $team->id)->get('user_id')->all();
        $players = [];
        foreach ($playerIds as $playerId) {
            foreach ($allPlayers as $player) {
                if($player->id == $playerId->user_id) {
                    array_push($players, $player);
                }
            }
        }

        return $players;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Tournament $tournament)
    {
        $teams = Team::all();
        $maps = DB::table('map')->get()->all();
        $team1 = DB::table('team_tournament')->where('tournament_id', $tournament->id)->get()->first()->team_id;
        $team2 = DB::table('team_tournament')->where('tournament_id', $tournament->id)->get()->last()->team_id;

        return view('tournament.edit', compact('teams', 'maps', 'tournament', 'team1', 'team2'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Tournament $tournament)
    {
        $team1 = $request->team1;
        $team2 = $request->team2;

        if($team1 != $team2) {
            $tournamentData = [
                'name' => $request->name,
                'map_id' => $request->map_id
            ];

            $tournament->update($tournamentData);
            DB::table('team_tournament')->where('tournament_id', $tournament->id)->delete();
            $tournament->attachTeam()->attach($team1);
            $tournament->attachTeam()->attach($team2);

            return redirect()->route('tournament.index')->with('success', 'Tournament was updated.');
        }

        return redirect()->route('tournament.create')->with('error', 'Same teams cant play with each other');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Tournament $tournament)
    {
        $players = User::all();
        $tournamentTeamSql = DB::table('team_tournament')->where('tournament_id', $tournament->id);
        $tournamentTeamIds = $tournamentTeamSql->get('team_id')->all();
        $team1 = Team::find($tournamentTeamIds[0]->team_id);
        $team2 = Team::find($tournamentTeamIds[1]->team_id);
        $playersTeam1 = $this->getTeamsPlayers($team1, $players);
        $playersTeam2 = $this->getTeamsPlayers($team2, $players);
        $this->deletePlayerStats($playersTeam1);
        $this->deletePlayerStats($playersTeam2);
        $tournamentTeamSql->delete();
        $tournament->delete();

        return redirect()->route('tournament.index')->with('success', 'Tournament was deleted.');
    }

    /**
     * @param $players
     */
    public function deletePlayerStats($players) {
        foreach ($players as $player) {
            DB::table('stats_user')->where('user_id', $player->id)->delete();
        }
    }
}

laraveldarbs/resources/views/tournament/changeScore.blade.php
@extends('layouts.app')
@section('content')

    <div class="form-container">
        <form class="new-challenge-form" method="post" enctype="multipart/form-data" action="{{ route('tournament.updateScore', $tournament) }}">
            @csrf
            @method('PUT');
            <h3>Update score</h3>
            <div class="form-group">
                <label>Score</label>
                <input class="form-control" type="text" name="score" required minlength="3" value="{{ $tournament->score }}">
            </div>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Submit</button>
        </form>
    </div>

@endsection

laraveldarbs/resources/views/tournament/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="form-container">
        <form class="new-challenge-form" method="post" enctype="multipart/form-data" action="{{ route('tournament.store') }}">
            @csrf
            <h3>New Tournament</h3>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" name="name" required minlength="4">
            </div>
            <div class="form-group">
                <label>Team 1</label>
                @if(json_encode($teams) != '[]')
                    <select class="form-select" name="team1" id="map-select">
                        @foreach($teams as $team)
                            <option value="{{ $team->id }}">
                                {{ $team->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no teams') }}</div>
                        @endif
                    </select>
            </div>
            <div class="form-group">
                <label>Team 2</label>
                @if(json_encode($teams) != '[]')
                    <select class="form-select" name="team2" id="map-select">
                        @foreach($teams as $team)
                            <option value="{{ $team->id }}">
                                {{ $team->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no teams') }}</div>
                        @endif
                    </select>
            </div>
            <div class="form-group">
                <label>Map</label>
                @if(json_encode($maps) != '[]')
                    <select class="form-select" name="map_id" id="map-select">
                        @foreach($maps as $map)
                            <option value="{{ $map->id }}">
                                {{ $map->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no maps') }}</div>
                        @endif
                    </select>
            </div>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Submit</button>
        </form>
    </div>

@endsection

laraveldarbs/resources/views/tournament/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="form-container">
        <form class="new-challenge-form" method="post" enctype="multipart/form-data" action="{{ route('tournament.update', $tournament) }}">
            @csrf
            @method('PUT');
            <h3>Edit Tournament</h3>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" name="name" required minlength="4" value="{{ $tournament->name }}">
            </div>
            <div class="form-group">
                <label>Team 1</label>
                @if(json_encode($teams) != '[]')
                    <select class="form-select" name="team1" id="map-select">
                        @foreach($teams as $team)
                            <option value="{{ $team->id }}" {{ $team->id == $team1 ? 'selected' : ''   }}>
                                {{ $team->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no teams') }}</div>
                        @endif
                    </select>
            </div>
            <div class="form-group">
                <label>Team 2</label>
                @if(json_encode($teams) != '[]')
                    <select class="form-select" name="team2" id="map-select">
                        @foreach($teams as $team)
                            <option value="{{ $team->id }}" {{ $team->id == $team2 ? 'selected' : ''   }}>
                                {{ $team->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no teams') }}</div>
                        @endif
                    </select>
            </div>
            <div class="form-group">
                <label>Map</label>
                @if(json_encode($maps) != '[]')
                    <select class="form-select" name="map_id" id="map-select">
                        @foreach($maps as $map)
                            <option value="{{ $map->id }}" {{ $map->id == $tournament->map_id ? 'selected' : ''   }}>
                                {{ $map->name }}
                            </option>
                        @endforeach
                        @else
                            <div class="form-control">{{ __('There are no maps') }}</div>
                        @endif
                    </select>
            </div>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Submit</button>
        </form>
    </div>

@endsection

laraveldarbs/resources/views/tournament/index.blade.php
@extends('layouts.app')
@section('content')
    <a class="btn btn-success" href="{{ route('tournament.create')  }}">Create tournament</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Tournament</th>
            <th scope="col">Map</th>
            <th scope="col">Team 1</th>
            <th scope="col">Team 2</th>
            <th scope="col">Created at</th>
            <th scope="col">Updated at</th>
            <th scope="col">Options</th>
        </tr>
        </thead>
        <tbody>
        @foreach($tournaments as $tournament)
            <tr>
                <td>{{ $tournament->name }}</td>
                <td>{{ getMapName($maps, $tournament->map_id) }}</td>
                <td>{{ getTeamName($teams, $tournamentTeam, $tournament->id, 1) }}</td>
                <td>{{ getTeamName($teams, $tournamentTeam, $tournament->id, 2) }}</td>
                <td>{{ $tournament->created_at }}</td>
                <td>{{ $tournament->updated_at }}</td>
                <td>
                    <form action="{{ route('tournament.destroy',$tournament) }}" method="POST">
                        <a href="{{ route('tournament.show', $tournament ) }}" class="btn btn-success">Look</a>
                        @auth()
                            {{--                            @if(Auth::user()->role == 'administrator')--}}
                            <a href="{{ route('tournament.edit', $tournament) }}" class="btn btn-info">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                            {{--                            @endif--}}
                        @endauth
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

laraveldarbs/resources/views/tournament/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <a class="btn btn-primary" href="{{ route('tournament.getChangeStatsView', $tournament) }}">Change stats</a>
    <a class="btn btn-primary" href="{{ route('tournament.changeScore', $tournament) }}">Change score</a>
    <div class="row">
        <div class="col-sm">
            <h3>{{ $team1->name  }}</h3>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Player</th>
                    <th scope="col">Kills</th>
                    <th scope="col">Assists</th>
                    <th scope="col">Deaths</th>
                </tr>
                </thead>
                <tbody>
                @foreach($playersTeam1 as $player)
                    <tr>
                        <td>{{ $player->name }}</td>
                        <td>{{ getPlayerKills($player)  }}</td>
                        <td>{{ getPlayerAssists($player) }}</td>
                        <td>{{ getPlayerDeaths($player) }}</td>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-sm">
            <h3>{{ $team2->name }}</h3>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Player</th>
                    <th scope="col">Kills</th>
                    <th scope="col">Assists</th>
                    <th scope="col">Deaths</th>
                </tr>
                </thead>
                <tbody>
                @foreach($playersTeam2 as $player)
                    <tr>
                        <td>{{ $player->name }}</td>
                        <td>{{ getPlayerKills($player)  }}</td>
                        <td>{{ getPlayerAssists($player) }}</td>
                        <td>{{ getPlayerDeaths($player) }}</td>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <h1 class="score" style="width: 100%; text-align: center;">{{ $tournament->score }}</h1>
</div>
@endsection

laraveldarbs/resources/views/tournament/showPlayerStats.blade.php
@extends('layouts.app')
@section('content')
    <form class="new-challenge-form" method="post" enctype="multipart/form-data" action="{{ route('tournament.addStats', $tournament) }}">
        @csrf
        <button class="btn btn-success" type="submit">Save</button>
        <div class="row">
                <div class="col-sm">
                @foreach($playersTeam1 as $player)
                    <div class="form-group">
                        <label>{{ $player->name }}</label>
                        <br/>
                        <span>Kills</span>
                        <input class="form-control" type="number" name="{{ $player->id.'kills' }}" required min="0" value="{{ getPlayerKills($player) }}">
                        <span>Assists</span>
                        <input class="form-control" type="number" name="{{ $player->id.'assists' }}" required min="0" value="{{ getPlayerAssists($player) }}">
                        <span>Deaths</span>
                        <input class="form-control" type="number" name="{{ $player->id.'deaths' }}" required min="0" value="{{ getPlayerDeaths($player) }}">
                    </div>
                @endforeach
                </div>
                <div class="col-sm">
                    @foreach($playersTeam2 as $player)
                        <div class="form-group">
                            <label>{{ $player->name }}</label>
                            <br/>
                            <span>Kills</span>
                            <input class="form-control" type="number" name="{{ $player->id.'kills' }}" required min="0" value="{{ getPlayerKills($player) }}">
                            <span>Assists</span>
                            <input class="form-control" type="number" name="{{ $player->id.'assists' }}" required min="0" value="{{ getPlayerAssists($player) }}">
                            <span>Deaths</span>
                            <input class="form-control" type="number" name="{{ $player->id.'deaths' }}" required min="0" value="{{ getPlayerDeaths($player) }}">
                        </div>
                    @endforeach
                </div>
        </div>
    </form>
@endsection